extends:
  - "@commitlint/config-conventional"

rules:
    type-enum:
      - 2
      - always
      - ["feat", "docs", "refactor", "test", "chore", "style", "fix"]
    subject-full-stop: [0, "never"]
    subject-case: [0, "never"]
